### ISSUE TITLE
Calling on chromosome X

### ISSUE THREAD

**Issue by Akazhiel** [WGLab/NanoCaller#14]
Hello!

I've checked that NanoCaller only calls SNPs and Indels for chromosomes 1-22 and I was wondering why the chromosome X gets excluded from the variant calling? I would assume is due to the models having been trained on these chromosomes, but I still would know why chromosome X is left out.

Best regards,

Jonatan

**Comment by umahsn** [comment]
Hi,

We used chr1-22 as a default option because we thought that would be the most likely usage, but users can specify any chromosome for variant calling. In particular, using `-wgs_contigs_type all` option will run NanoCaller on all sequences present in reference fasta file. We will update the default option to include chrX and chrY as well. We did test out models on chrX of NA12878 and found same performance as for other chromosomes, even though none of our models were trained on chrX.
