### ISSUE TITLE
Error: Resource temporarily unavailable 

### ISSUE THREAD

**Issue by huangnengCSU** [WGLab/NanoCaller#17]
Hi,
     When I ran NanoCaller to find variants  with ONT data, the program exited without completing execution. There are some failed information.
```
OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 766195 max
```
I used 48 cpu threads and the memory is 256GB.

Best 
Neng

**Comment by umahsn** [comment]
Hi Neng,

I am assuming that you are using NanoCaller_WGS.py to run NanoCaller because that's where I have seen this problem before. This is happening because NanoCaller is running 48 tensorflow sessions, one in each thread, which can exceed the number of processes allowed.

Here are a few suggestions that can help:

1. Run `ulimit -u unlimited` command in terminal as suggested here: https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable.
2. Use fewer threads than 48, perhaps 16 or 24.
3. Use docker container to run NanoCaller. I have noticed that the problem you mentioned goes away when I use docker to run NanoCaller instead.
4. Use NanoCaller.py command instead for each contig individually. If you use any number of CPUs with this command, it creates only one tensorflow session and uses other threads for feature generation only.

I am looking at reorganizing/reimplementing parallelism in NanoCaller_WGS.py in a way that it also creates only one tensorflow session but that might take some time.

Let me know if this helps,
Umair

**Comment by huangnengCSU** [comment]
To umahsn:
    It works when I tested the two command you provided. Thanks a lot.

Best
Neng
